import type { NextPage } from "next";
import { signOut } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";
import SignOutButton from "./components/SignOutButton";

const Home: NextPage = () => {
  const getSession = trpc.useQuery(["auth.getSession"]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        {!getSession.data ? (
          <Link href="/api/auth/signin">
            <a>Sign in with Twitch</a>
          </Link>
        ) : (
          <>
            <Link href="/dashboard">
              <a>Go to dashboard</a>
            </Link>
            or
            <SignOutButton />
          </>
        )}
      </div>
    </>
  );
};

export default Home;
